version: "3.8"

services: 
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        ports:
            - 27017:27017
        networks: 
            - app_node_network
    redis:
        container_name: redis
        image: redis:5
        ports:
            - 6379:6379
        networks: 
            - app_node_network
    app-node:
        container_name: app-node
        image: java-docker:1.0
        ports: 
            - 8080:8080
        depends_on: 
            - redis
            - mongo
        environment:
            - NAME=docker
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks: 
            - app_node_network

networks:
    app_node_network:
        name: app_node_network